/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'features',
    path: '/features',
    component: 'layout.base$view.features',
    meta: {
      title: 'features',
      i18nKey: 'route.features',
      localIcon: 'activity',
      order: 2
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      localIcon: 'banner',
      order: 0
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'licenses',
    path: '/licenses',
    component: 'layout.base$view.licenses',
    meta: {
      title: 'licenses',
      i18nKey: 'route.licenses',
      localIcon: 'heart',
      order: 4
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'plans',
    path: '/plans',
    component: 'layout.base$view.plans',
    meta: {
      title: 'plans',
      i18nKey: 'route.plans',
      localIcon: 'cast',
      order: 3
    }
  },
  {
    name: 'projects',
    path: '/projects',
    component: 'layout.base$view.projects',
    meta: {
      title: 'projects',
      i18nKey: 'route.projects',
      localIcon: 'custom-icon',
      order: 1
    }
  }
];
